### ISSUE TITLE
Arrow pngs not loading on ios build

### ISSUE THREAD

**Issue by jamount** [amareque/react-native-simple-accordion#2]
The arrows show up fine on expo go but when i build the app they do not show for ios. Any ideas why this might be?

**Comment by amareque** [comment]
Hi! I'll have to check it out.

What are you using to build the app? eas-cli or expo build? 

I'll circle back to you once I check this in the next few days. Thanks for letting me know!

**Comment by amareque** [comment]
Hi! It's been a long time hahaha, I just updated all the libraries and it is showing correctly for me. I'll close this issue but feel free to try the latest version (v2.0.2) and let me know!
