### ISSUE TITLE
How to detect accordion is expanded or not?

### ISSUE THREAD

**Issue by mertavcioglu** [amareque/react-native-simple-accordion#3]
How to detect accordion is expanded or not? There is no Touchable Opacity or any props to it.

I wrote isExpanded constants but I cannot use them.

```
<SimpleAccordion
      key={index}
      viewInside={renderFertilizersForMonth(fertilizers)}
      titleStyle={styles.titleStyle}
      title={
        <View style={styles.titleContainer}>
          <Text style={styles.titleTextStyle}>{`${index} .AY`}</Text>
        </View>
      }
      bannerStyle={[
        styles.bannerStyle,
        {
          backgroundColor: bgColor,
          width: isExpanded
            ? Dimensions.get("window").width
            : Dimensions.get("window").width - 40,
          borderBottomLeftRadius: isExpanded ? 0 : 50,
          borderBottomRightRadius: isExpanded ? 0 : 50,
          borderTopLeftRadius: isExpanded ? 50 : 50,
          borderTopRightRadius: isExpanded ? 50 : 50,
        },
      ]}
      viewContainerStyle={[
        styles.viewContainerStyle,
        {
          backgroundColor: bgColor,
          marginTop: isExpanded ? -60 : 10,
          paddingTop: isExpanded ? 70 : 10,
        },
      ]}
    />
```

**Comment by amareque** [comment]
Hey! I was just starting to work on updating this library. 

Right now it seems like there is no way to know from outside. I'll try to include it in the next release!
I'm leaving this issue open to circle back here if I'm able to get it implemented :) 

Thanks!

**Comment by amareque** [comment]
Hey! Sorry for the delay 😅 

I've added a callback to check get the state of the accordion
Now, if you want to know if the accordion is expanded you can have your own variable or use a ref to check the isCollapsed attribute of the component

I also added functions to open, close or toggle programatically 😉 

I'd recommend you to check out the npm home page to know more. Version is 2.0.2 now

Thanks! :)

**Comment by amareque** [comment]
I'll close the issue for now, let me know if it works for you!
